version: '3.8'
    
services:
  app:
    build: .
    image: django
    restart: unless-stopped
    tty: true
    volumes:
      - .:/code
    ports:
      - "9000:9000"
    # depends_on:
    #   - db
    # working_dir: /code
    networks:
      - app-network

# volumes:
#   db-volume: 

networks:
  app-network:
    driver: bridge

